[tool.poetry]
name = "cq-electronics"
version = "0.1.0"
description = "Pure CadQuery models of various electronic boards and components."
authors = ["Seth Fischer <seth@fischer.nz>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
